import os
import smtplib
import requests
import google.generativeai as genai
from email.mime.text import MIMEText
from email.header import Header
from datetime import datetime

# --- 配置区域 ---
NEWS_API_KEY = os.environ["NEWS_API_KEY"]
EMAIL_USER = os.environ["EMAIL_USER"]
EMAIL_PASS = os.environ["EMAIL_PASSWORD"]
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY") # 获取 AI Key

TARGET_EMAIL = EMAIL_USER

# 配置 Gemini
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
    # 使用 flash 模型，速度快且免费额度高
    model = genai.GenerativeModel('gemini-pro')

def get_news():
    # 获取全球科技/商业新闻 (你可以改 category=general)
    url = f"https://newsapi.org/v2/top-headlines?country=us&category=general&pageSize=7&apiKey={NEWS_API_KEY}"
    try:
        response = requests.get(url)
        data = response.json()
        return data.get("articles", [])
    except Exception as e:
        print(f"获取新闻失败: {e}")
        return []

def ai_summarize(title, description):
    """调用 Gemini 进行翻译和总结"""
    if not GEMINI_API_KEY:
        return description # 如果没配置 Key，就返回原版

    try:
        # 给 AI 的指令 (Vibe Prompt)
        # Vibe Prompt 2.0: 拒绝翻译腔，更像人话
        prompt = f"""
        你是一位有着10年经验的资深国际新闻编辑。
        请阅读以下英文新闻，用**最地道、最符合中国人阅读习惯**的中文重写一段简报（100字以内）。
        
        关键要求：
        1. 🚫 **拒绝翻译腔**：严禁逐字直译！不要出现“它是被...”这种被动句态。
        2. 🗣️ **说人话**：用中文的逻辑重新组织语言，读起来要顺口、自然。
        3. 🎯 **抓重点**：直接告诉读者发生了什么事，省略次要的修饰词。
        
        英文标题: {title}
        英文简介: {description}
        
        中文摘要：
        """
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"AI 总结失败: {e}")
        return description # 失败回退

def send_email(articles):
    if not articles:
        print("没有新闻可发")
        return

    today = datetime.now().strftime("%Y-%m-%d %A")
    print(f"正在处理 {len(articles)} 条新闻，AI 正在阅读中... (这可能需要几十秒)")

    # --- 邮件头部 ---
    html_content = f"""
    <html>
    <body style="font-family: 'Helvetica Neue', Helvetica, 'Microsoft YaHei', sans-serif; background-color: #f4f4f4; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1);">
            <div style="text-align: center; border-bottom: 2px solid #000; padding-bottom: 15px; margin-bottom: 25px;">
                <h1 style="color: #000; font-size: 26px; margin: 0;">🌍 全球早报 (AI 版)</h1>
                <p style="color: #666; font-size: 14px; margin-top: 5px;">{today} | Gemini 整理</p>
            </div>
    """

    # --- 循环处理每条新闻 ---
    for article in articles:
        title_en = article.get('title', '无标题')
        desc_en = article.get('description', '')
        url = article.get('url')
        source = article.get('source', {}).get('name', 'Unknown')

        if title_en == "[Removed]": continue

        # === 关键步骤：召唤 AI ===
        # 传入标题和简介，获取中文总结
        summary_cn = ai_summarize(title_en, desc_en)

        html_content += f"""
            <div style="margin-bottom: 30px; padding: 15px; background-color: #f9f9f9; border-radius: 8px; border-left: 4px solid #007bff;">
                <h3 style="margin: 0 0 10px 0; font-size: 18px; line-height: 1.4;">
                    <a href="{url}" style="color: #2c3e50; text-decoration: none;">{title_en}</a>
                </h3>
                <div style="font-size: 12px; color: #888; margin-bottom: 8px;">
                    来源: {source}
                </div>
                <p style="color: #333; font-size: 15px; line-height: 1.6; margin: 0;">
                    <strong>💡 AI 划重点：</strong> {summary_cn}
                </p>
            </div>
        """

    html_content += """
            <div style="margin-top: 30px; text-align: center; color: #aaa; font-size: 12px;">
                Generated by GitHub Actions & Google Gemini
            </div>
        </div>
    </body>
    </html>
    """

    # --- 发送逻辑 ---
    msg = MIMEText(html_content, 'html', 'utf-8')
    msg['From'] = Header("AI News Bot", 'utf-8')
    msg['To'] = TARGET_EMAIL
    msg['Subject'] = Header(f"早安！今日全球要闻 ({today})", 'utf-8')

    try:
        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(EMAIL_USER, EMAIL_PASS)
        server.sendmail(EMAIL_USER, [TARGET_EMAIL], msg.as_string())
        server.quit()
        print("✅ 邮件发送成功！")
    except Exception as e:
        print(f"❌ 发送失败: {e}")

if __name__ == "__main__":
    articles = get_news()
    send_email(articles)
